import type { Area, Species } from "@/types/fishing";
export const areas: Area[] = [
  {
    id: "10000000-0000-4000-8000-000000000001",
    slug: "kepulauan-seribu",
    name: "Kepulauan Seribu",
    description:
      "Gugusan pulau, terumbu karang, dan perairan terbuka di utara Jakarta. Jelajahi potensi mancing di tepian karang dan laut lepas.",
    latitude: -5.65,
    longitude: 106.58,
    timezone: "Asia/Jakarta",
    marine_zone_name: "Perairan Kepulauan Seribu",
  },
  {
    id: "10000000-0000-4000-8000-000000000002",
    slug: "bekasi-karawang",
    name: "Bekasi–Karawang",
    description:
      "Perairan pesisir utara Jawa Barat dengan muara, dasar berlumpur, dan perairan dangkal. Pilihan untuk mancing dasar dan casting.",
    latitude: -5.85,
    longitude: 107.15,
    timezone: "Asia/Jakarta",
    marine_zone_name: "Perairan Karawang",
  },
];
const fish = [
  [
    "Tenggiri",
    "tenggiri",
    "Scomberomorus commerson",
    "Predator pelagis yang sering diburu di tepian karang.",
    "Laut terbuka, tepian karang",
    15,
    50,
    25,
    31,
    ["Trolling", "Casting"],
    ["Minnow", "Ikan hidup"],
    [4, 5, 6, 7, 8, 9, 10],
  ],
  [
    "Kuwe",
    "kuwe",
    "Caranx ignobilis",
    "Ikan kuat penghuni terumbu dan perairan berarus.",
    "Terumbu karang, drop-off",
    5,
    60,
    25,
    31,
    ["Popping", "Jigging"],
    ["Popper", "Metal jig"],
    [4, 5, 6, 7, 8, 9],
  ],
  [
    "Kakap Merah",
    "kakap-merah",
    "Lutjanus malabaricus",
    "Ikan demersal yang berasosiasi dengan struktur dasar laut.",
    "Karang dalam, struktur dasar",
    20,
    100,
    24,
    30,
    ["Bottom fishing", "Slow jigging"],
    ["Cumi", "Ikan potong"],
    [3, 4, 5, 9, 10, 11],
  ],
  [
    "Kakap Putih",
    "kakap-putih",
    "Lates calcarifer",
    "Predator pesisir dan muara dengan toleransi salinitas luas.",
    "Muara, mangrove, pesisir",
    1,
    20,
    26,
    32,
    ["Casting", "Bottom fishing"],
    ["Udang hidup", "Minnow"],
    [1, 2, 3, 10, 11, 12],
  ],
  [
    "Kerapu",
    "kerapu",
    "Epinephelus spp.",
    "Kelompok ikan karang yang mencari makan dekat struktur.",
    "Karang, bebatuan dasar",
    5,
    80,
    25,
    31,
    ["Bottom fishing", "Jigging"],
    ["Ikan hidup", "Cumi"],
    [3, 4, 5, 6, 9, 10],
  ],
  [
    "Talang-talang",
    "talang-talang",
    "Scomberoides commersonnianus",
    "Predator pesisir yang dapat dijumpai dekat permukaan.",
    "Pesisir, muara, permukaan",
    1,
    30,
    26,
    32,
    ["Casting", "Trolling"],
    ["Spoon", "Minnow"],
    [5, 6, 7, 8, 9],
  ],
  [
    "Barracuda",
    "barracuda",
    "Sphyraena spp.",
    "Predator bergigi tajam di sekitar terumbu dan perairan terbuka.",
    "Terumbu, laut terbuka",
    5,
    60,
    25,
    31,
    ["Trolling", "Casting"],
    ["Minnow", "Ikan hidup"],
    [4, 5, 6, 7, 8, 9, 10],
  ],
  [
    "Tongkol",
    "tongkol",
    "Euthynnus affinis",
    "Ikan pelagis berkelompok yang mengikuti ketersediaan pakan.",
    "Laut terbuka, perairan pesisir",
    10,
    100,
    24,
    30,
    ["Trolling", "Casting"],
    ["Feather lure", "Metal jig"],
    [5, 6, 7, 8, 9, 10],
  ],
  [
    "Cobia",
    "cobia",
    "Rachycentron canadum",
    "Predator laut yang dapat mengikuti struktur terapung.",
    "Struktur terapung, laut terbuka",
    5,
    80,
    25,
    31,
    ["Casting", "Jigging"],
    ["Ikan hidup", "Soft plastic"],
    [4, 5, 6, 9, 10],
  ],
  [
    "Lemadang",
    "lemadang",
    "Coryphaena hippurus",
    "Ikan pelagis yang sering berasosiasi dengan benda terapung.",
    "Laut lepas, rumpon",
    5,
    80,
    25,
    30,
    ["Trolling", "Casting"],
    ["Skirt lure", "Ikan hidup"],
    [5, 6, 7, 8, 9],
  ],
] as const;
export const species: Species[] = fish.map((f, i) => ({
  id: `20000000-0000-4000-8000-${String(i + 1).padStart(12, "0")}`,
  name: f[0],
  slug: f[1],
  scientific_name: f[2],
  description: f[3],
  image_url: `/fish/${f[1]}.jpg`,
  habitat: f[4],
  min_depth: f[5],
  max_depth: f[6],
  preferred_temperature_min: f[7],
  preferred_temperature_max: f[8],
  techniques: [...f[9]],
  bait: [...f[10]],
  months: [...f[11]],
  areas: f[1] === "lemadang" ? ["kepulauan-seribu"] : areas.map((a) => a.slug),
}));
